### ISSUE TITLE
Lines are not aligned properly

### ISSUE THREAD

**Issue by fathergorry** [anseki/leader-line#231] opened 2021-05-14 15:40 UTC
When creating new LeaderLine just after the document is loaded, or on document.ready in jQuery, it is positioned a bit off-side, some pixels left or right to the margin it's attached. Both start and end has the same offset.
This offset is passing away on window.resize: after resize, lines become aligned properly. 

My current workaround is to add .position() on every line, on every page event, but this makes my project to work very slow.

**Comment by anseki** [comment] 2021-05-14 16:05
Hi @fathergorry, thank you for the comment.
What is the "page event"?
To reproduce that, could you show an example by using e.g. https://jsfiddle.net/ ?

**Comment by fathergorry** [comment] 2021-05-15 04:48
Hi, thanks a lot for reply. 
I've upgraded to Chrome 90 and the bug seem have passed away.

In an older version, this code resulted in line offset about 4px left and 4px top.

`<html>

<table border=1 width=100%>
<tr><td id="section1">section 1</td><td id="section2" width=200></td><td id="section3">section 3</td></tr>
</table>

<script src="plugins/leader-line.min.js"></script>

<script>
 		var from = document.getElementById("section1");
		var to = document.getElementById("section3");
		new LeaderLine( from, to);
</script>

</html>`

**Comment by anseki** [comment] 2021-05-15 05:16
I see.
This bug in your code is the creating new line without waiting for the document to be loaded.
The bug is fixed by creating new LeaderLine after the document is loaded. For example:
```js
addEventListener('load', () => {
  new LeaderLine(document.getElementById('section1'), document.getElementById('section3'));
});
```
So, could you close this issue if it was solved?

**Comment by anseki** [comment] 2021-05-21 01:47
No reply came, then this abandoned issue is closed.

**Closed by anseki** 2021-05-21 01:47 UTC

**Comment by anseki** [comment] 2021-09-01 02:29
Hi @ShinkarenkoMaksim, thank you for the comment.
You have to wait for the document to be loaded if your page layout is changed when it is loaded. If your code waits that correctly, the `position()` method is not required.

**Comment by fathergorry** [comment] 2021-09-01 08:12
I finally end up with 0.5s timeout after document.ready() and before repeating position(). 
Also, a setInterval of 0.5-2sec with position() may help.

**Comment by anseki** [comment] 2021-09-01 08:20
If the `document.ready` you said is `$(document).ready` of jQuery, you are mistaken about `DOMContentLoaded` event and `load` event.
See document: https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event

**Comment by ShinkarenkoMaksim** [comment] 2021-09-01 15:34
> Hi @ShinkarenkoMaksim, thank you for the comment.
> You have to wait for the document to be loaded if your page layout is changed when it is loaded. If your code waits that correctly, the `position()` method is not required.

Yes, of course I am waiting for document.load () to complete. Perhaps this is due to the peculiarity of yii2 pjax widget, since content is loaded through this widget.

**Comment by anseki** [comment] 2021-09-01 16:11
I see.
That is, you mean that you didn't wait for the document to be loaded. You have to wait for the document to be loaded by using other than the `load` event.
You have to hook your Yii widget finishing loading something instead, or you have to specify size for `<img>` or something to avoid changing layout when those are loaded.
