### ISSUE TITLE
Inject document in component

### ISSUE THREAD

**Issue by user007-u** [anseki/leader-line#100] opened 2020-01-30 11:11 UTC
I try to inject a document into curent component and draw a line with leadr-line
```js
import {DOCUMENT} from '@angular/common';
import 'leader-line/leader-line.min';
declare const LeaderLine: any;
@Component({
 selector: 'app-component1',
})
export class Component1 implements OnInit{
constructor(@Inject(DOCUMENT) private document) {
}

createLine(){
const line = new LeaderLine(
        this.document.getElementById('remainder'),
        this.document.getElementById('button0')
    )
}

}
```
this component is used in another component
```js
@Component({
selector: 'app-component2',

})
export class Component2 implements OnInit {

constructor() { }

ngOnInit() {
}
```
```html
<tab>

 <app-component1>

 </app-component1>
</tab>
```
but instead of that, the line is displayed in the background not in componet1.

Maybe you could help me .
Thank you

**Comment by anseki** [comment] 2020-01-30 14:30
Hi @user007-u, thank you for the comment.
Could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by user007-u** [comment] 2020-01-30 15:19
Unfortunately I couldn't make an example, I tried stackblitz but it doesn't work, 
here is an image to illustrate the problem
![pr](https://user-images.githubusercontent.com/33081921/73462476-88516080-4384-11ea-8202-55eb33bfe0cf.png)

**Comment by anseki** [comment] 2020-01-31 01:14
Can you use anything that is online coding service to reproduce that?
e.g.
- [CodePen](http://codepen.io/)
- [JS Bin](http://jsbin.com/)
- [Plunker](http://plnkr.co/)
- [Liveweave](http://liveweave.com/)
- and others...

**Comment by user007-u** [comment] 2020-01-31 09:46
Finally, I have an example in stackblitz (https://stackblitz.com/edit/angular-wx5guo), the problem is when I have mat-sidenav-container  (https://angular-wx5guo.stackblitz.io/b) the line is drawn in the background, instead of the component. If I have a simple view the line is drawn(https://stackblitz.com/edit/angular-wx5guo?file=src%2Fapp%2Fside%2Fside.component.html/b). To draw a line clik on text1 and text2.

**Comment by anseki** [comment] 2020-01-31 16:24
Lines should be added to `body` element.
You might have to adjust those style.

**Comment by user007-u** [comment] 2020-01-31 16:46
Can you help me with this? I tried something but doesn't work (https://stackblitz.com/edit/angular-wx5guo). Thank you!

**Comment by anseki** [comment] 2020-02-01 00:43
I don't know result that you expect, but your example seems to work without problem.
See this:
https://angular-8og83o.stackblitz.io
Could you explain the problem?

**Comment by user007-u** [comment] 2020-02-01 12:52
In this case(https://angular-8og83o.stackblitz.io) it's ok, but in this https://angular-8og83o.stackblitz.io/b the line is not displayed. Also  in the first case (https://angular-8og83o.stackblitz.io) 
I also wish that in the first case I try to make the line to stay connected with the object when you drag one of them.

**Comment by user007-u** [comment] 2020-02-01 13:00
In this case(https://angular-8og83o.stackblitz.io) it's ok, but in this https://angular-8og83o.stackblitz.io/b the line is not displayed. Also in the first case (https://angular-8og83o.stackblitz.io)
I also wish that in the first case I try to make the line to stay connected with the object when you drag one of them. Thank you very much!

**Comment by anseki** [comment] 2020-02-01 14:43
See this:
https://github.com/anseki/leader-line/issues/100#issuecomment-580803515
https://angular-nqduvt.stackblitz.io/b

**Comment by user007-u** [comment] 2020-02-01 17:57
Thank you, now the line is displayed, but I try to make the line to stay connected with the object when you drag text1(https://stackblitz.com/edit/angular-tvxsbc) and it is possible that the line does not cross the border?
![pr1](https://user-images.githubusercontent.com/33081921/73596676-ede05100-452c-11ea-91f7-1fc51ef4905b.png)

**Comment by anseki** [comment] 2020-02-01 23:02
I couldn't understand the your question because the elements can move over the borders.
You can specify connection point of the line.
It is possible to avoid that the line crosses the border when the elements are positioned at same position in the your image.
https://angular-h7wx1m.stackblitz.io

**Comment by user007-u** [comment] 2020-02-02 07:24
I want the line to stay connected with the object when you drag the object, but the line remain in the old position.
Here in an example 
![pr2](https://user-images.githubusercontent.com/33081921/73604685-523af900-459d-11ea-8203-23afa4e7313d.png)

**Comment by anseki** [comment] 2020-02-02 07:38
Sorry, do you mean that the line is connecting when the line crosses the border?

**Comment by user007-u** [comment] 2020-02-02 07:45
No, I expect : when I move(drag) the object, the line moves with the object
![pr3](https://user-images.githubusercontent.com/33081921/73604901-3edd5d00-45a0-11ea-927b-949bda1b3d7e.png)

**Comment by anseki** [comment] 2020-02-02 08:18
Ummm...
What kind of relation does the dragging have to the crossing?

**Comment by user007-u** [comment] 2020-02-02 08:20
I do not understand what you mean

**Comment by anseki** [comment] 2020-02-02 08:20
Do you mean that the issue about the crossing was already solved?

**Comment by user007-u** [comment] 2020-02-02 08:24
No, when an object is moved 
![pr3](https://user-images.githubusercontent.com/33081921/73605367-03de2800-45a6-11ea-9703-b1c49b428a01.png)

**Comment by user007-u** [comment] 2020-02-02 08:45
I try to have the same behavior as here (https://anseki.github.io/leader-line/)
![exp](https://user-images.githubusercontent.com/33081921/73605610-08f0a680-45a9-11ea-9627-8706c5a5f498.png)

**Comment by anseki** [comment] 2020-02-02 08:54
Sorry, my English is poor. What do you mean?
Did you read this?
https://github.com/anseki/leader-line/issues/100#issuecomment-581078552

**Comment by user007-u** [comment] 2020-02-02 19:51
It work. Thank you!

**Comment by anseki** [comment] 2020-02-02 22:49
:smile: 
Could you close this issue if it was solved?

**Comment by user007-u** [comment] 2020-02-03 09:13
Hi,
I have the following question: it is possible to draw a line by select with click the start point and the line following the mouse until you select the end? Thank you! Here is an example
![f](https://user-images.githubusercontent.com/33081921/73639996-25a6e000-4676-11ea-9ec8-c021d6bd435f.png)

**Comment by anseki** [comment] 2020-02-03 10:16
@user007-u,
Could you close this solved issue? And could you make new issue for another topic?

**Closed** 2020-02-03 10:19 UTC
