### ISSUE TITLE
Leading lines show on other pages

### ISSUE THREAD

**Issue by Esom** [anseki/leader-line#157] opened 2020-08-31 13:52 UTC
<img width="331" alt="Screen Shot 2020-08-31 at 2 50 23 PM" src="https://user-images.githubusercontent.com/622885/91727268-58c43a00-eb99-11ea-991f-1e36ef71f1bc.png">
<img width="339" alt="Screen Shot 2020-08-31 at 2 49 06 PM" src="https://user-images.githubusercontent.com/622885/91727289-624da200-eb99-11ea-9cfe-1fe254661759.png">

Hello , Good work on this library it has really helped me in accomplishing my tasks, but i have just one issue, my leading lines show on other pages

This is an ionic app

**Comment by anseki** [comment] 2020-09-01 00:44
Hi @Esom, thank you for the comment.
Could you explain about result you expect?
Also, could you show me an example to reproduce that by using e.g. https://jsfiddle.net/ ?

**Comment by Esom** [comment] 2020-09-02 07:55
Hi @anseki , thanks for your swift response, I fixed the issue by hiding all leader-line when i leave the page

**Comment by colmoneill** [comment] 2020-09-02 08:08
Hi all,
Thank you for this library, it has been a joy to use.
I seem to be facing a similar issue to @Esom I'm using LeaderLine on the homepage of a website, but the lines are reappearing on other pages that do not have the HTML elements that are present on the homepage:

website homepage: http://breadfellows.school/ (you will see the leader lines on the top) — screeshot below
![Screenshot_2020-09-02 Breadfellows school](https://user-images.githubusercontent.com/2122318/91955656-70b3cf00-ecfb-11ea-83da-72a18e7ca56d.png)

but then on all of the other pages of this (still in development) website, I see little horizontal leader lines in what seems to be a mix of colours from the initial homepage settings. See the two screenshots attached below:
![Screenshot_2020-09-02 Breadfellows school(1)](https://user-images.githubusercontent.com/2122318/91955648-6db8de80-ecfb-11ea-80af-652f48fc30da.png)
![Screenshot_2020-09-02 Breadfellows school](https://user-images.githubusercontent.com/2122318/91955653-6f82a200-ecfb-11ea-8772-7db4b9f4a82e.jpg)

Am I forgetting to do something or is this a bug? I'm primarily using Firefox 78.0.1 (64-bit) on Manjaro Linux, but this is happening in my other test browsers too.

Thanks for any info,

Cheers

**Comment by anseki** [comment] 2020-09-02 09:20
@Esom, I'm glad if I could help you. :smile: 
Could you close this issue if it was solved?

**Comment by anseki** [comment] 2020-09-02 09:21
Hi @colmoneill, thank you for the comment.
Could you make new issue for another topic?

**Closed** 2020-09-11 23:29 UTC
