### ISSUE TITLE
Viewport

### ISSUE THREAD

**Issue by Martin-N** [anseki/leader-line#13] opened 2018-06-05 11:00 UTC
There is no option to specify where to append the line SVG. It would be good to be able to specify a specific element / viewport to append the SVG.

This would fix the issue if you draw the lines inside a scrollable element. Currently if it is inside a scrollable element we have to run the position method while scrolling which isn't very performant and the line is drawn on top which makes it able to go outside the element instead of disappearing underneath while it is scrolled.

**Comment by anseki** [comment] 2018-06-05 11:27
Hi @Martin-N, thank you for the comment.

Sorry, my English is poor.
Do you mean that you want to append a leader line to a scrollable element to make it follow scrolling that element?

**Comment by Martin-N** [comment] 2018-06-05 13:12
Yes, and so that the line is not visible outside it's container. See attached pic. The line should not be visible outside the orange block. 

If I move the SVG element inside this container manually, then it displays correctly as in it doesn't appear outside it's container and it scrolls with the content, but then it's position is off.

![line](https://user-images.githubusercontent.com/1511317/40977919-8ea86048-68d2-11e8-9a3f-6a030ba8ec7d.jpg)

**Comment by anseki** [comment] 2018-06-12 01:28
No reply came, and I close this issue.

**Closed by anseki** 2018-06-12 01:28 UTC

**Comment by sarnold04** [comment] 2018-07-09 21:05
Hi @anseki,

I'm currently working on a project where this feature could be very useful. Do you have any idea about modifying your code so that a div could be specified as base document where the whole svg stuff is added?

**Comment by anseki** [comment] 2018-07-10 07:57
Hi @sarnold04, thank you for the comment.
SVGs are now added to the document but you can move those.
Note that the moving is not supported because those should avoid being affected by other elements or something.

**Comment by sarnold04** [comment] 2018-07-10 20:05
Hi @anseki,

thanks for your quick response. I will move them after the lines have been added.

**Comment by anseki** [comment] 2018-07-11 03:23
:smile:

**Comment by b4nt0** [comment] 2019-01-01 10:46
Hi @anseki, in order for us to move the element manually, is it possible that you please expose an accessor to insProps[].svg?
Then we could move the element cleanly, without having to search for it in the DOM.

**Comment by anseki** [comment] 2019-01-01 12:02
Hi @b4nt0, thank you for the comment.
The moving the element is not supported because that should avoid being affected by other elements or something.
Therefore you can move the element by yourself (i.e. hacky method) only if you understand those and the structure of the DOM.

**Comment by b4nt0** [comment] 2019-01-02 10:03
Hi @anseki, thank you for the explanation! I think the "hacky method" will not work well, since there's no reliable way to recognize the SVG.
In order to avoid positioning and overlap issues, another method could probably work, such as clipping. This needs exposure of the SVG too though. What are you thoughts on this?

**Comment by anseki** [comment] 2019-01-02 10:32
@b4nt0,
Sorry, my English is poor.
Do you mean that the `querySelector` method could not get the SVG element?
Could you explain about your code?
Also, what do you want to do with the element? e.g. masking

**Comment by b4nt0** [comment] 2019-01-02 10:44
@anseki your English is excellent :)
What I mean is that the <svg> element that you create does not have any distinctive attribute that I can filter on, e.g. no ID. The only place where you store a link is in insProp list, which is internal. 
Therefore reliably finding the svg element related to a certain LeaderLine seems impossible.
--
Regarding my code to handle it - the code does not exist yet. I thought of clipping.

**Comment by anseki** [comment] 2019-01-02 12:13
The `querySelector` method can get a certain SVG element that was added last time.
However, that is hacky method as I said.
The easy way that is not hacky method to clip the line is the adding another window in current document (i.e. `iframe`).
Since LeaderLine supports multiple windows, you can clip the line by adding the line to separated `iframe`.

**Comment by frumbert** [comment] 2020-02-14 08:40
The svg elements are attached to the dom root node (e.g body), but in this example there is a scrolling element that isn't the body - it's a div with overflow deeper in the dom tree. Scrolling this pane doesn't reflect the position of the svg elements, as noted in this issue and others.

![connection-scrolling](https://user-images.githubusercontent.com/592257/74514855-892bea00-4f61-11ea-9e1b-2e6d04ba95ec.gif)

What is your recommended course of action for this problem, if any?

**Comment by anseki** [comment] 2020-02-14 09:55
Hi @frumbert, thank you for the comment.
This example may help you.
https://github.com/anseki/leader-line/issues/54#issuecomment-500712640

**Comment by frumbert** [comment] 2020-02-14 12:51
I've taken steps to move the node into the scrolling element so that the overflow will crop/hide the svg lines as required. I've then used the negative transform you suggest (or negative margin which also works though less performant via repaints) to reposition the elements.

```javascript
// 'scrollable' is my overflowing element; scrollableBbox is its bounding client rect
Array.from(document.querySelectorAll(".leader-line")).forEach(function(elem) {
    elem.style.transform = "translate(-" + (scrollable.scrollTop + scrollableBbox.x) + "px, -" + scrollableBbox.y + "px)";
    scrollable.appendChild(elem);
});
```

This is ok until you scroll at which point the setting line.position() repositions the `top` style property without taking into account the scrollTop; and similar for the `left` property.

![connection-scrolltop](https://user-images.githubusercontent.com/592257/74531289-5cd39600-4f80-11ea-95a2-c8e97f1fd5b9.gif)

I'm using PlainDraggable to move the nodes. 

```javascript
// 'end' is the draggable node
    const draggable = new PlainDraggable(end, {
        onMove: function () { line.position(); },
        onMoveStart: function () { line.dash = { animation: true }; },
        onDragEnd: function () { line.dash = false; },
        autoScroll: end.closest(".overflow")
    });
```

inside `onMove` I have a reference to `line` but it does't seem to have any exposed property referring to the `<svg class='line-leader' ...` DOM element which the line is drawn by, which I would need in order to set the transform property again to take into account the scroll offset myself. Can I infer which `<svg>` element a `line` belongs to - or is it just nth-child?

Is there a reason the `position()` method doesn't (or can't be made to) accept `scrollTop / scrollLeft` 
when calculating the `top` and `left` style properties during its update?

I am currently keeping an array of the line objects and iterating obect and hoping they match the order of the `svg` elements I moved into the scrollable node area. This seems pretty jank and breaks more places than it works, and means I'm reapply the `transform` property ever time the AnimEvent/scroll event triggers, rather than just when the draggable node moves. I could move the transform calculation back to the onMove function but then I still don't have a reference to the equivalent underlying `svg` DOM element.

**Comment by anseki** [comment] 2020-02-14 14:20
Hi @frumbert.
Sorry, my English is poor.
Do you mean that the example didn't help you?
Could you show me your example by using e.g. https://jsfiddle.net/ ?

**Comment by frumbert** [comment] 2020-02-14 21:55
Attaching the leader line to a child object and _then scrolling the object_ doesn't take into account the scrolling offset when calling `line.position()`.

https://jsfiddle.net/frumbert/Lhpvmw7d/10/

![jsfiddle](https://user-images.githubusercontent.com/592257/74570582-c4b1cd00-4fd0-11ea-9bf5-54475fde4f2a.gif)

How can I get the `position()` method to respect the scrolling offset of the wrapper when it recalculates?

**Comment by anseki** [comment] 2020-02-15 00:17
You don't need the `position()` method that respects the scrolling offset because you already did that by using the wrapper. That is, you only have to fix the position of the wrapper.
And also, it seems that you misunderstood `autoScroll` option.
https://jsfiddle.net/to5b4srx/

**Comment by frumbert** [comment] 2020-02-15 01:40
Yes this example is much clearer. I was worried on the performace of calling getBoundingClientRect so frequently (e.g. every time onMove fires) but if I cache it or use AnimEvent the tracking position breaks - so I guess I'll have to live with it. Thanks for your assistance!

**Comment by anseki** [comment] 2020-02-15 02:12
I'm glad if I could help you. :smile: 
If you consider the performance, you can call the `wrapperPosition()` only once only when that was scrolled.
Foe example:
https://jsfiddle.net/zqhv32a1/

**Comment by frumbert** [comment] 2020-02-16 00:48
Hmm, i _thought_ I knew what my problem was until I put leader line into my box which has scrolling. The page itself never scrolls but a box within it does, so in the wrapperPosition function I offset by the scroll position of the overflowing container. Scrolling also updates the position of the wrapper.

I made a complete fiddle using all my current [unfinished] source, rather than a quick cut down example. Code needs a cleanup. https://jsfiddle.net/frumbert/m5acL241/2/

The steps to reproduce the issue I am seeing are:

1. Make the results window reasonably wide and short enough that it shows a scroll bar.
2. Drag a couple of leader lines to their connectors (dots)
3. Scroll the window down a bit - note the leader lines appear to scroll with the page
4. drag another leader line.

The position of the last leader line is now incorrect but the other leader lines still appear in the correct positions.

Here is an animation showing what I see:

![scroll-issue](https://user-images.githubusercontent.com/592257/74597325-dfa83e00-50b1-11ea-953b-32876d5b7990.gif)

**Comment by anseki** [comment] 2020-02-16 08:02
Hi @frumbert, did you read my comment?

**Comment by frumbert** [comment] 2020-02-16 08:55
Yes, I read your comment and your code and based my reply on it, as you can see by me adopting your code into my example. Thanks for taking the time.

Since posting my problem, I've gone back to the drawing board since leader-line obviously can't work properly when the svgs are appended somewhere other than the root - there are too many issues relating to scrolling. Perhaps you could mention in your documentation that moving the svgs from the body into an overflowing object isn't reccomended? It would save a lot of fiddling about.

I've re-engineered my example page so that there isn't a scrolling container and rather let the body element be the scrolling container - as you probably intended.

https://jsfiddle.net/frumbert/dL96gta5/3/ is effectively **working as intended** (nearly).

![reload-issue](https://user-images.githubusercontent.com/592257/74601741-721e0100-50f5-11ea-96a4-092f2b6c6c09.gif)

**Comment by anseki** [comment] 2020-02-16 10:16
I think your first mistake is that you misunderstood `getBoundingClientRect` method. Then you miscalculated the position.
Your second mistake is that you overlooked my comment that I said that I never recommend moving SVG elements because that is not supported.
It is better for you to use another library that you like because it seems that you don't need LeaderLine.

**Comment by Mahesh9959-mahi** [comment] 2020-07-29 09:56
Hi @anseki,
When I tried to vertical scroll the Links are going out of bound, I have tried with  following 

var elmSvgClip = document.getElementsByClassName('leader-line'),
   elmClipRect = document.getElementById('leader-line-46-mask-bg-rect'),
   posPoint = elmSvgClip.createSVGPoint();

But i'm getting elmSvgClip.createSVGPoint() is not a function error and weird behaviour of link. I have attached the screenshot of links for your reference, Can you help how we can fix this, By the way I'm creating the links dynamically..!

![LinksOverflowIssue](https://user-images.githubusercontent.com/68947472/88785465-da960180-d1ae-11ea-8684-eef7363ebafa.PNG)

**Comment by anseki** [comment] 2020-07-29 10:54
Hi @Mahesh9959-mahi, thank you for the comment.
Try this:
```js
console.log(elmSvgClip);
```
Maybe, `elmSvgClip` is `undefined`.

**Comment by anseki** [comment] 2020-07-29 10:57
Ah, it is `HTMLCollection` maybe.
Try the `elmSvgClip[0]` instead.

**Comment by Mahesh9959-mahi** [comment] 2020-07-29 12:34
Hi @anseki,
Thanks for your response, Now I'm able to get the SVG with elmSvgClip, But when I scroll still i'm getting same issue. 
Here is my code to drawlinks dynamically and I have added few lines of code for scroll, Please have a look. Thanks in advance

var me = this;
        var linksData = this.state.links;
        var connList = [];
        var color;
        this.clearLinks();
        this.clearCompareData();
        var elemWrapper = document.getElementById('canvasTreeContainer');
        var elmFrame = document.getElementById('canvasTreeContainer');
        var rectWrapper = elemWrapper.getBoundingClientRect();
       var rectFrame = elmFrame.getBoundingClientRect();
       var  FRAME_LEFT = rectFrame.left;
   var FRAME_TOP = rectFrame.top;
  var FRAME_RIGHT = FRAME_LEFT + elmFrame.clientWidth;
  var FRAME_BOTTOM = FRAME_TOP + elmFrame.clientHeight;
        if(linksData !== undefined && linksData !== null) {
            Object.keys(linksData).map(function(key){
                if(linksData[key] && linksData[key].status === 1) {
                    color = '#03b075';
                } else if(linksData[key].status === 0) {
                    color = '#fbca33';
                } else {
                    color = '#e4002b';
                }
                var x = document.getElementById("node_" + linksData[key].ExternalBreakdownId1 + '_' + linksData[key].ExternalNodeId1);
                var source = x && x.offsetParent && x.offsetParent.parentElement;
                var y = document.getElementById("node_" + linksData[key].ExternalBreakdownId2 + '_' + linksData[key].ExternalNodeId2);
                var target = y && y.offsetParent && y.offsetParent.parentElement;
                if (source && target && source!==null && target!==null) {
                    var line = new window.LeaderLine(source, target, {  
                        dash: {animation: true},
                        size: 4,
                        color: color,
                        startSocket: 'auto',
                        endSocket: 'auto',
                        
                        endPlug: 'arrow1'
                    })
                    var elmLine = document.querySelector('body>.leader-line>g:last-of-type');
                    var elmSvgClip = document.getElementsByClassName('leader-line');
                    var elmClipRect = document.getElementById('leader-line-46-mask-bg-rect');
                    if(elmSvgClip[0]!==undefined){
                     var posPoint = elmSvgClip[0].createSVGPoint();
                      }
                    if(elmLine) {
                    elmLine.id = linksData[key].Id;
                    elmLine.addEventListener('click', (e)=>{
                        e.preventDefault();
                        var connectionId = e.currentTarget.id;
                        if(connectionId) me.getLinkData(parseInt(connectionId));
                    });
                    }
                    connList.push(line);
                    elemWrapper.appendChild(document.querySelector('body>.leader-line:last-of-type'));
                } else if(source!==null && (!target || target===null)) {
                    var elem = document.getElementById('linkIcon' + linksData[key].ExternalNodeId1);
                    if(elem) {
                    elem.setAttribute('class', 'linkExpandIcon');
                    var btnVal = elem.offsetParent.value;
                    if(!btnVal || btnVal==="") {
                        btnVal = linksData[key].ExternalNode2Path.toString();
                    } else if(!btnVal.includes(linksData[key].ExternalNode2Path.toString())){
                        btnVal = btnVal + "," + linksData[key].ExternalNode2Path;
                }
                    elem && elem.offsetParent.setAttribute('value', btnVal);
            }
                } else if((!source || source===null) && target!==null) {
                    var elem = document.getElementById('linkIcon' + linksData[key].ExternalNodeId2);
                    if(elem) {
                    elem.setAttribute('class', 'linkExpandIcon');
                    var btnVal = elem.offsetParent.value;
                    if(!btnVal || btnVal==="") {
                        btnVal = linksData[key].ExternalNode1Path.toString();
                    } else if(!btnVal.includes(linksData[key].ExternalNode1Path.toString())){
                        btnVal = btnVal + "," + linksData[key].ExternalNode1Path;
                    }
                    elem && elem.offsetParent.setAttribute('value', btnVal);
                }
                }
                function update() {
             if(posPoint!=undefined){
                    function docPoint2svgPoint(point) {
                      posPoint.x = point.x;
                      posPoint.y = point.y;
                      return posPoint.matrixTransform(elmSvgClip.getScreenCTM().inverse());
                    }
                
                    line.position();
                    // Synchronize coordinate system
                    elmSvgClip.style.left = elmLine.style.left;
                    elmSvgClip.style.top = elmLine.style.top;
                    // Get the coordinates of the rect
                    var pointLT = docPoint2svgPoint({x: FRAME_LEFT, y: FRAME_TOP});
                     var pointRB = docPoint2svgPoint({x: FRAME_RIGHT, y: FRAME_BOTTOM});
                    // Adjust the clip
                    elmClipRect.x.baseVal.value = pointLT.x;
                    elmClipRect.y.baseVal.value = pointLT.y;
                    elmClipRect.width.baseVal.value = pointRB.x - pointLT.x;
                    elmClipRect.height.baseVal.value = pointRB.y - pointLT.y;
                  }
                  
                      if(elmLine!==undefined){
                  elmLine.style.clipPath = 'url(#clip)';
                  elmFrame.addEventListener('scroll', this.AnimEvent.add(update), false);
                  update();
                
                }
                  }
            });
            var LinkNodeCount = [];
         linksData.forEach(function(v) {
            LinkNodeCount[v.UniqueTextIdForNodeId1] = (LinkNodeCount[v.UniqueTextIdForNodeId1] || 0) + 1;
          })
       this.state.LinkNodeCount= LinkNodeCount;
       
      
        }

**Comment by Mahesh9959-mahi** [comment] 2020-07-29 14:11
while scrolling controller is not hitting the upadate()

**Comment by anseki** [comment] 2020-07-29 15:50
Unfortunately your code didn't work. It seems that the code that you indicated is a part of code.
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by Mahesh9959-mahi** [comment] 2020-07-29 16:06
https://jsfiddle.net/heuj7mso/  I have same issue what ever they discribed, But in my case **AnimEvent** getting not defined error and controller not hitting **elmLine.style.clipPath = 'url(#clip)';** line

**Comment by Mahesh9959-mahi** [comment] 2020-07-30 01:20
Hi @anseki,

Is there any way to change the lines from body to specific div, It's targeting the body that's why it's overlapping headers as well

**Comment by anseki** [comment] 2020-07-30 03:11
You can do that, but it seems that you already did that.
This is your code:
```js
elemWrapper.appendChild(document.querySelector('body>.leader-line:last-of-type'))
```

These also may help you:
https://github.com/anseki/leader-line/issues/25
https://github.com/anseki/leader-line/issues/54

**Comment by Mahesh9959-mahi** [comment] 2020-07-30 03:45
Why **AnimEvent**  is giving undefined, I have added     <script src="anim-event.min.js"></script> as well

**Comment by anseki** [comment] 2020-07-30 05:23
To reproduce that, could you show me an example by using e.g. https://jsfiddle.net/ ?

**Comment by whxleemdddd** [comment] 2021-04-27 04:05
let rect_l=$('.note_page_div').offset().left;
    let rect_t=$('.note_page_div').offset().top;
    let rect_b=($('.note_page_div').offset().top+$('.note_page_div').height()+$('.note_page_div').scrollTop())+'px';
    let rect_r=($('.note_page_div').offset().left+$('.note_page_div').width()+$('.note_page_div').scrollLeft())+'px';
     for(let line of lines){
        line.position();
    } 
     $('.leader-line').each(function(){
         let svg_t=(rect_t-$(this).offset().top)+'px';
         let svg_l=(rect_l-$(this).offset().left)+'px';
        $(this)[0].style.clip='rect('+svg_t+','+rect_r+','+rect_b+','+svg_l+')'
    })
    $('.leader-line-areaAnchor').each(function(){
        let svg_t=(rect_t-$(this).offset().top)+'px';
        let svg_l=(rect_l-$(this).offset().left)+'px';
       $(this)[0].style.clip='rect('+svg_t+','+rect_r+','+rect_b+','+svg_l+')'
    })

**Comment by anseki** [comment] 2021-04-27 05:00
Hi @whxleemdddd, thank you for the comment.
What is that?

**Comment by AhmedAyachi** [comment] 2022-06-27 16:51
I created a leaderline class extension please check this https://github.com/AhmedAyachi/LeaderLine

**Comment by anseki** [comment] 2022-06-28 05:03
Hi @AhmedAyachi, thank you for the comment.
Unfortunately, many tests failed, However, your special library might be useful for your app. :smile:
