### ISSUE TITLE
Import in create-react-app

### ISSUE THREAD

**Issue by supra28** [anseki/leader-line#12] opened 2018-05-31 12:52 UTC
Is there a way to use this library with create-react-app ?
The only way I was able to use it was including it in a script tag inside index.html
and then inside of my component I had to use ` window.LeaderLine` 
This seems very hacky

**Comment by anseki** [comment] 2018-05-31 13:55
Hi @supra28, thank you for the comment.
I think that Webpack or the script tag is easy way to use the library.

**Comment by supra28** [comment] 2018-05-31 14:42
Hmm i'll look around in case i find a cleaner way to do this, I'll post it here when I find more.

**Comment by anseki** [comment] 2018-05-31 15:01
Ok, thanks. :smile: 
You may find a tool more simple than Webpack. 
It should be easy because the create-react-app also uses Webpack by default.

**Comment by supra28** [comment] 2018-05-31 15:41
Can you tell me why is it that we can't import this module directly like
 `import LeaderLine from "leader-line"`
and we have to use a loader for it?
Is it possible that we can fix this in this place itself, that would make it easier for others to create wrappers around this library to use it with there frameworks.

**Comment by anseki** [comment] 2018-05-31 15:59
The LeaderLine now is provided as ES5, not ES2015.
Therefore, you can import that into your script easily by using the skeleton-loader that inserts the export statement.
For example, this may help you: https://github.com/anseki/leader-line/issues/8

**Comment by supra28** [comment] 2018-05-31 16:23
Oh I did see that , maybe I wasn't clear earlier , I wan't to know if there could be a way to export this module from here itself so it doesn't require any webpack configuration, Doing webpack config would require everyone to eject their create-react-app which isn't very ideal.

**Comment by supra28** [comment] 2018-05-31 17:00
One way to do it would be to just add module.exports = LeaderLine at the end of the leader-line.js file in the source
Will doing this cause any problems in the build process?

**Comment by supra28** [comment] 2018-05-31 17:32
**Update** I forked this repo and made necessary change and ran grunt to build , every thing works fine and then I ran `npm run test` and Initially when I forked 6 tests seemed to be failing but after the change only 5 fail for some reason lol 👯‍♂️ 

I also tested my fork to display a simple line in a project using import and it works fine. 

I can send you a pull request if you want.

**Comment by anseki** [comment] 2018-06-01 00:36
Yes, as you said, that changing will cause serious problems about compatibility. Therefore, you should use that only in your project.
Also, that changing now is not needed because it seems that is almost the same as changing by skeleton-loader I indicated.

The most recommended way is the way using loader because the library was designed as ES5 as I said.

BTW, you should use `export default` instead of `module.exports` in your code because that is CommonJS that might be not supported in some environment.

So, can you close this issue because it was solved?

**Comment by supra28** [comment] 2018-06-01 02:30
Actually it didn't cause compatibility issues, but you can close this issue i'll maintain a seperate fork of this project.

**Comment by anseki** [comment] 2018-06-01 03:20
There are very serious problems about compatibility. Therefore, you should use that only in your project.

Anyway, as you said, it seems that this issue was already solved by your forked library, and I close this issue. :smile:

**Closed by anseki** 2018-06-01 03:20 UTC

**Comment by aweibell** [comment] 2018-12-11 14:16
A Javascript library in 2018 should definitely be possible to import directly into a create-react-app! Please consider reopening this issue and restructure your code as suggested by @supra28

**Comment by anseki** [comment] 2018-12-11 16:12
Hi @aweibell, thank you for the suggestion.
I now think that the refactoring is not needed because it can be imported via Webpack and `import` statement.
Also, this library is old and it is hardly necessary for many cases.
However, I might rethink that someday. Thank you. :smile:

**Comment by AnonymousArthur** [comment] 2019-08-06 01:37
@anseki Hey bro, it's 2019 now. Have you changed your mind?

**Comment by anseki** [comment] 2019-08-06 02:01
Hi @AnonymousArthur, thank you for your comment.
Do you mean that the Webpack is old now?
I still think that this library is old and it is hardly necessary for many cases.
You had better choose another library if you think that the Webpack and this library are old.

**Comment by AnonymousArthur** [comment] 2019-08-06 06:21
@anseki exports-loader can partially solve this importing problem, but not an elegant solution. It'll be nice if your package support import as a module. BTW, after importing this package I found rendered lines are not re-rendered when page height changed (target DOM is absolute position + bottom positioning), but re-rendered when page resized.

**Comment by anseki** [comment] 2019-08-06 07:36
I recommended the skeleton-loader.
You can make new issue for another problem.

**Comment by sorahn** [comment] 2019-08-17 20:01
If anyone else finds their way to this issue trying to use this with react, I solved the import issue by using a `postinstall` script to just append the following line to the end of the file.

`if (module && module.exports) { module.exports = LeaderLine }`

The full script looks like this:
```bash
#!/bin/bash

if grep -q 'module.exports = LeaderLine' ./node_modules/leader-line/leader-line.min.js; then
  echo 'Leader Line already patched'
else
  echo "\
    if (module && module.exports) { module.exports = LeaderLine }\
  " >> ./node_modules/leader-line/leader-line.min.js
fi;
```
@anseki in a create-react-app with out ejecting there is no access to the webpack config.  I really don't see why you wouldn't be able to have this module work properly, and not need another package to load it.

**Comment by sorahn** [comment] 2019-08-17 20:05
> I found rendered lines are not re-rendered when page height changed (target DOM is absolute position + bottom positioning), but re-rendered when page resized.

@AnonymousArthur monitor the height of the document and run `<line>.position()` when it changes.  Where <line> is what `new LeaderLine()` returns

**Comment by anseki** [comment] 2019-08-18 02:46
Hi @sorahn, thank you for the information. :smile:

**Comment by amostech** [comment] 2020-05-22 19:54
Man, please rethink! We need this feature. It's 2020. Have you changed your mind? If you do please publish a new npm version with this MAGIC ONE LINE!

`if (module && module.exports) { module.exports = window.LeaderLine }`

Do you think we should not use leader-line alongside with react due to compatibility issues?

**Comment by anseki** [comment] 2020-05-23 02:19
Hi @amostech, thank you for the suggestion.
I might rethink that someday. Thank you. :smile: 
BTW, you should use `export default` instead of `module.exports`.
