### ISSUE TITLE
when can this library support fabricjs objec/element ? 

### ISSUE THREAD

**Issue by 7hihi** [anseki/leader-line#72] opened 2019-10-04 12:29 UTC
I fount this library. It is so cool, but it dose not support fabricjs object. 
I need the fabricjs object can connect by leaderline.

**Comment by anseki** [comment] 2019-10-04 18:30
Hi @7hihi, thank you for the comment.
So, do you mean that you want to use the LeaderLine with [Fabric.js](http://fabricjs.com/) in canvas element?

**Comment by 7hihi** [comment] 2019-10-06 09:43
yeah, if you do it, that is perfect!!!

**Comment by anseki** [comment] 2019-10-06 10:34
Maybe you are having a misunderstanding.
Fabric.js is a library to handle canvas easily. LeaderLine is a library to draw a leader line in web page, and it has nothing to do with canvas because it uses SVG.
Therefore, nobody wants LeaderLine to support Fabric.js, and of course it should not do that.

If you need a feature to draw a leader line with Fabric.js object in canvas, you have to request that to Fabric.js repository, not here.
If you want to handle SVG easily, you can use a SVG wrapper library such as [Snap.svg](http://snapsvg.io/) or another.

**Comment by 7hihi** [comment] 2019-10-06 12:46
maybe you are right, but i have to draw a line between fabricjs's objects. 
Currently, i draw a line by  LeaderLine.pointAnchor. 
The difficulty is that my cannot handle the line easily. 
I know that the best method is that draw a svg line in canvas. but the coding is so hard....

Anyway thanks a lot, by the way, could help me draw a line like lealderline in fabricjs's canvas. 
I can pay for you work.

**Comment by anseki** [comment] 2019-10-06 13:49
No, you are still having a misunderstanding.
Mixing SVG and canvas is not good idea, and it is never  the best method.
Those have different own view. Therefore, that method is not easy as you said, and it may make hacky code.

The best and easy way is that draw lines in canvas by using canvas features, and this is optimum solution because canvas was designed for drawing something like this case. Methods to draw a line are provided by canvas (e.g. `lineTo`, `bezierCurveTo`, `arcTo`, etc.).
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial
That is, you don't have to use SVG at all to draw lines in canvas.

As I said, If you need a feature to draw a line by Fabric.js, you have to request that to Fabric.js repository.

**Comment by anseki** [comment] 2019-10-12 03:16
No reply came, then I close this abandoned issue.

**Closed by anseki** 2019-10-12 03:16 UTC

**Comment by anseki** [comment] 2019-10-12 03:29
FYI, this is an example:
https://jsfiddle.net/jmgs8v7c/
If the draggable object is not required, the code should be more simple.

This is an example that uses LeaderLine, if you really need it:
https://jsfiddle.net/kq4myobc/
