### ISSUE TITLE
'A disconnected element was passed' error after removing a line with line.remove() and try to set options using line.setOptions() to the line with the latest '_id' property

### ISSUE THREAD

**Issue by Eliav2** [anseki/leader-line#111] opened 2020-03-29 13:36 UTC
Hey there,
I'm using leader-line in react project as a 3rd lib to draw lines between elements.
first of all, here's a codesandbox:   https://codesandbox.io/s/leaderline-bug-elnex
to reproduce the bug:
1. press on any mod box (but not mod4) and press delete on the top bar showing. - the element will be removed and any lines connected to him (using line.remove()).
2. now select the element with the last _id which is mod4.
and 'A disconnected element was passed. Cannot read property 'right' of null.' error will be thrown by leader-line.
this is happening after using line.remove() or line.hide().

does line.setOptions() changing the _id property of a line if line.remove() (or line.hide() ) was called on a difrrent line before?

I'm frustrated for days and can't fix this.. 
help will be very appreciated!

**Comment by anseki** [comment] 2020-03-30 00:34
Hi @Eliav2, thank you for the comment.
That is correct behavior because a removed line should not work anymore.
See document: https://anseki.github.io/leader-line/#remove

**Comment by Eliav2** [comment] 2020-03-30 02:06
this is not correct behavior. lines changing their anchors when removing other lines.
for example - in this example, removing line mades every other line that put after him take the anchor defined for the next line.
for example -  removing line1 will make line2 to move from mod2 to mod3 on next update and line3 to mod4.
choose selecte the elements(the mod boxes) to trigger an update to the line connecting to them.
(do so:
1. delete mod1 and select mod3 and see how it the arrow connect to mod2 now updates to connect  mod3.
1. delete mod2 and select mod4 and see how the arrow connect to mod3 now updates to mod4, but because the arrow of mod4 try to updates.
please check the console.logs and see what the line.start and line.end elements - before deleting and after deleting.
the anchors of the other lines change even though no function touched them directly it all it my code.

this is probably a problem with your library and not my code.
there is an leader-line.js file(not leader-line.min.js) that i can add to my project that i can read and debug my self? i cant debug leader-line.min.js

**Comment by anseki** [comment] 2020-03-30 04:30
Sorry, my English is poor. Could you explain about reproducing that?
I did this:
1. I clicked the `mod2` element. Then, the element became gray.
2. I clicked the `Delete` button on the top.
3. The error that you said has not occurred.

**Comment by Eliav2** [comment] 2020-03-30 09:39
sorry friend - I edited the code - but now I reproduced the problem.
1. click the mod2 element. Then, the element became gray.
2. click the Delete button on the top.
3. click on mod4 element - The error will occur.

I think this is happening because removing a line using line.remove() causes other lines to change their anchors. please see my previous comment for a detailed explanation.

**Comment by anseki** [comment] 2020-03-30 15:21
I see.
As I said, that is correct behavior.
LeaderLine should throw an error (that says "A disconnected element was passed.") because you passed a disconnected element.
An easy way to fix the bug in your code:
https://codesandbox.io/s/leaderline-bug-hfwdt
Note that this is not a solution to the root of the problem because your code has a bug about logic.

**Comment by Eliav2** [comment] 2020-03-30 16:18
thank you for the help my friend - I've moved to React suited library instead.
(consider making adjustments to your library and support React - this is a great library and can very popular among React developers - such library in such quality does not exist in React yet)

**Comment by anseki** [comment] 2020-03-30 16:27
I'm glad if I could help you. :smile: 
And thank you for the comment.
So, could you close this issue if it was solved?

**Closed** 2020-03-30 18:33 UTC
